apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: seyoawe
resources:
  - ../../base
images:
  - name: sawe-engine
    newName: 403113723064.dkr.ecr.us-east-1.amazonaws.com/sawe-engine
    newTag: latest
  - name: sawe-cli
    newName: 403113723064.dkr.ecr.us-east-1.amazonaws.com/sawe-cli
    newTag: latest
