# Dockerfile for CLI tests

FROM python:3.12-slim
WORKDIR /workspace

# Copy the CLI, tests, and the data they reference
COPY cli/ cli/
COPY engine/modules/ engine/modules/
COPY engine/workflows/ engine/workflows/
COPY cli/tests-cli/ cli/tests-cli/

# Install the CLI requirements and pytest
RUN pip install --no-cache-dir -r cli/requirements.txt

# Run both unit and integration tests
CMD ["pytest", "cli/tests-cli/", "-v"]


### Can simply access locally the cli using:
### docker run -it cli-test:latest bash

### Build image using this dockerfile and repo root as context:
### docker build -f docker/Dockerfile.cli_test -t cli-test ..

# Run test image:
# docker run --rm cli-test