# Dockerfile for Engine tests

FROM python:3.12-slim
WORKDIR /workspace

# Copy exactly how the test expects the structure
COPY engine/ engine/
COPY tests/engine/ tests/engine/

# Install system dependencies and Python requirements
RUN apt update && apt install -y curl git
RUN pip install --no-cache-dir -r engine/requirements.txt pytest
EXPOSE 5000

# Make scripts executable
RUN chmod +x engine/run.sh engine/seyoawe.linux engine/seyoawe.macos.arm

# Make the docker container run the test automatically
CMD ["pytest", "tests/test_engine.py"]


### Build engine_test locally:
### docker build -f Dockerfile.engine_test -t engine-app ..
## ARM BUILD:
## docker build --platform linux/amd64 -f Dockerfile.engine_test -t engine-app ..


### Run engine_test locally:
### docker run -p 5000:5000 engine-app
## ARM RUN:
## docker run --platform linux/amd64 -p 5000:5000 engine-app 