# Dockerfile for CLI tests



FROM python:3.12-slim
WORKDIR /cli-test
COPY cli/ .
RUN pip install --no-cache-dir -r requirements.txt





### Can simply access locally the cli using:
### docker run -it cli-test:latest bash

### Build image using this dockerfile and main project directory:
### docker build -f Dockerfile.cli_test -t cli-test ..