# Dockerfile for Engine tests

FROM python:3.12-slim
WORKDIR /workspace

# Copy exactly how the test expects the structure
COPY engine/ engine/
COPY engine/tests-engine/ engine/tests-engine/

# Install system dependencies and Python requirements
RUN apt update && apt install -y curl git
RUN pip install --no-cache-dir -r engine/requirements.txt pytest pyyaml

# Make scripts executable
RUN chmod +x engine/run.sh engine/seyoawe.linux engine/seyoawe.macos.arm

# Run both unit and integration tests
CMD ["pytest", "engine/tests-engine/", "-v"]


### Build engine_test locally:
### docker build -f Dockerfile.engine_test -t engine-app ..
## ARM BUILD:
## docker build --platform linux/als
md64 -f Dockerfile.engine_test -t engine-app ..


### Run engine_test locally:
### docker run -p 5000:5000 engine-app
## ARM RUN:
## docker run --platform linux/amd64 -p 5000:5000 engine-app 