FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /opt/sawectl

COPY sawectl/requirements.txt /opt/sawectl/requirements.txt
RUN pip install --no-cache-dir -r /opt/sawectl/requirements.txt

COPY sawectl /opt/sawectl

ENTRYPOINT ["python", "/opt/sawectl/sawectl.py"]
