services:
  seyoawe-engine:
    build:
      context: ..
      dockerfile: docker/Dockerfile.engine
    image: seyoawe/engine:local
    container_name: seyoawe-engine
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ../configuration:/app/configuration
      - ../modules:/app/modules
      - ../workflows:/app/workflows
      - ../seyoawe-community/lifetimes:/app/seyoawe-community/lifetimes
      - ../seyoawe-community/logs:/app/seyoawe-community/logs
    restart: unless-stopped