apiVersion: apps/v1
kind: Deployment
metadata:
  name: sawe-engine
  labels:
    app.kubernetes.io/name: sawe-engine
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: sawe-engine
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sawe-engine
    spec:
      containers:
        - name: engine
          image: ronsss/sawe-engine:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 45
            periodSeconds: 20
