apiVersion: v1
kind: Service
metadata:
  name: sawe-engine
  labels:
    app.kubernetes.io/name: sawe-engine
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: sawe-engine
  ports:
    - port: 80
      targetPort: 8080
      name: http
