apiVersion: v1
kind: Service
metadata:
  name: sawe-engine
  labels:
    app.kubernetes.io/name: sawe-engine
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: sawe-engine
  ports:
    - name: http
      port: 80
      targetPort: http
